config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  get '/search', to: 'listings#search'

  get 'home/index'

  get 'tags/:tag', to: 'listings#index', as: :tag

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  resources :users, only: [:show, :edit, :update, :destroy]
  resources :listings do
    resources :reservations, only: [:new, :create, :destroy, :show]
  end
  resources :reservations, only: []

  resources :payments

end

app/models/listing.rb
class Listing < ActiveRecord::Base

  belongs_to :user
  has_many :reservations


  mount_uploaders :avatars, AvatarUploader

  acts_as_taggable # Alias for acts_as_taggable_on :tags

  searchkick match: :word_start, searchable: [:name, :location]

  #PART OF THE LOGIC FRO RESERVATION
  #In your Listing model, create a method that stores an array of reservations
  # dates upon creating, so it that people
  # cant book it twice(models/listing.rb)
  def booked_dates
      dates_tht_are_booked = []
      self.reservations.each do |reservation|
          reservation.dates.each do |date|
              dates_tht_are_booked <<date
          end
      end
      return dates_tht_are_booked

  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
# This is a fast way to require someting before. See set_listing method in private folder.
  before_action :set_listing, only: [:show, :update, :edit, :destroy]

  def index
    # if signed_in?
    #   redirect_to users_path
    # end
    @listings = Listing.all
  end

  def search
        @listings = Listing.search(params[:term], fields: ["title", "location"], mispellings: {below: 5})
        if @listings.blank?
          redirect_to listings_path, flash:{danger: "no successful search result"}
        else
          render :index
        end
  end

  def show
    @reservation = Reservation.new
  end


  def new
    @reservation = Reservation.new
    @listing = Listing.new

  end


  def create
    @listing = current_user.listings.new(listing_params)

      if @listing.save(validate: false)

      # I want o go to my listing show page
        redirect_to listings_path # This is the way to pass in an id
      else
        redirect_to new_listing_path
      end
  end


  # The def edit is already done automatically with the def set listing
  # def edit
  #   @listing = Listing.find(params[:id])
  # end

  def update
    if @listing.update(listing_params)

      # The next line is because I need to call the user_id parameter

      @listing.user_id = current_user.id
      redirect_to listing_path(@listing.id)
    else
      redirect_to edit_listing_path(@listing.id)
    end

  end

  def destroy
  @listing.destroy
  redirect_to user_path(current_user.id)
  end








 # We put this in private so nobody can see the all params

  private

  # The following method is called strong params see google
  def listing_params
    params.require(:listing).permit(:title, :location, :description, :daily_rate, :nb_room, :issmoker, :haslatecheckout, :haskitchen, :haswifi, :hasswimmingpool, :tag_list, :user_id, {unavdate:[]}, {avatars:[]})

  end

  def set_listing
    @listing = Listing.find(params[:id])

  end

  # This prevents us to retype it for every other method
  # so i don't have  to find the listing id for show, update edit, delete and destroy


  # def show
  # @listing = Listing.find(params[:id])
  # end
  # def edit
  # @listing = Listing.find(params[:id])
  # end
  # def update
  # @listing = Listing.find(params[:id])
  # end

end # -- >  end of class

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<!-- <form> -->
<%= form.file_field :avatars, multiple: true %>

  <div class="form-group">
    <%= form.label :Title %>
    <%= form.text_field :title, placeholder: "Enter Title", class: "form-control", id: "title" %>
  </div>

  <div class="form-group">
    <%= form.label :Location %>
    <%= form.text_field :location, placeholder: "Enter Location", class: "form-control", id: "location" %>
  </div>

  <div class="form-group">
    <%= form.label :Description %>
    <%= form.text_area :description, placeholder: "Enter description", class: "form-control", rows: "5", id: "description" %>
  </div>

  <div class="form-group">
    <%= form.label "Daily rate" %>
    <%= form.text_field :daily_rate, class: "form-control", id: "price_per_night" %>
  </div>

  <div class="form-group">
    <%= form.label "Number of rooms" %>
    <%= form.text_field :nb_room, class: "form-control", id: "nb_room" %>
  </div>

  <div class="form-group">
    <%= form.label "Smokers friendly" %>
    <%= form.check_box :issmoker, class: "form-control", id: "issmoker" %>
  </div>

  <div class="form-group">
    <%= form.label "We accept pets" %>
    <%= form.check_box :ispetfriendly, class: "form-control", id: "ispetfriendly" %>
  </div>

  <div class="form-group">
   <%= form.label "Allow check out at 2pm" %>
    <%= form.check_box :haslatecheckout, class: "form-control", id: "haslatecheckout" %>
  </div>

  <div class="form-group">
    <%= form.label "Kitchen + appliances" %>
    <%= form.check_box :haskitchen, class: "form-control", id: "haskitchen" %>
  </div>

  <div class="form-group">
    <%= form.label "Wifi available" %>
    <%= form.check_box :haswifi, class: "form-control", id: "haswifi" %>
  </div>

  <div class="form-group">
    <%= form.label "Swimming Pool" %>
    <%= form.check_box :hasswimmingpool, class: "form-control", id: "hasswimmingpool" %>
  </div>

  <div class = "form-group" >
  <%= form.label :tag_list %>
  <%= form.text_field :tag_list %>
  </div>

<!-- DAVID : Here I implement  a field which has to be linked to another form IE: fields are linked to Unavdates table and not the listing table.  There are two ways of doing it: nested forms or custom input field.  In this case it is input field -->


 <div class="form-group">
  <%=form.label :Unavailable_dates %>
    <script>
      $(function() {
      $("#resa_datepicker_end-<%=@listing.id %>" ).multiDatesPicker({
      dateFormat: 'dd-mm-yy',
      numberOfMonths: [3,4],
      altField: "#resa_datepicker_end_input",
      altFormat: "dd-mm-yy" }).val();
      });
    </script>
    <div id="resa_datepicker_end-<%=@listing.id %>"></div>
    <%=form.hidden_field :unavdate, class: "form-control", id: "resa_datepicker_end_input", :multiple => true %>
  </div>


<!-- var today = new Date();
$('#disable-dates').multiDatesPicker({
  addDisabledDates: [today.setDate(1), today.setDate(3)]
});
 -->


<!-- </form> -->

app/views/listings/edit.html.erb
<%= form_for @listing do |form| %>
    <%= render partial: '/listings/form', object: form %>
    <%= render partial: '/unavdates/form' %>

    <br>

    <div class="submit-field">
      <%= form.submit "Update Now", class: "btn btn-default"%>
    </div>

  <% end %>

app/views/listings/index.html.erb
<%@listings.each do |l|%>
<br>
<%= link_to "#{l.title}", listing_path(l.id) %><br>
    <%if l.avatars.present? %>
        <%= image_tag (l.avatars[0].square.url) %><br>
    <%end%>
        <%= l.location %>
        <br>
        <%= l.description %>
        <br>
        <%= l.description %>
        <br>
        <%= l.nb_room %>
        <br>
        <%= l.user_id %>

<%= link_to 'Book', new_listing_reservation_path(l.id)%>
<%end%>

<h2>Modal Example</h2>
  <!-- Trigger the modal with a button -->
  <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Open Modal</button>

app/views/listings/new.html.erb
this is a form to create a new listing
see partial form
<%= form_for @listing do |form| %>
    <%= render partial: '/listings/form', object: form %>
<!--     <%= render partial: '/unavdates/form' %> -->

    <br>

    <div class="submit-field">
      <%= form.submit "Create your listing", class: "btn btn-default"%>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>

app/views/listings/show.html.erb
<h1 >Listing Show page</h1>

<%= image_tag (@listing.avatars[0].square.url) %><br>
<%= @listing.title %>
<br>
<%= @listing.location %>
<br>
<%= @listing.description %>
<br>
<%= @listing.nb_room %>
<br>
<%= @listing.user_id %>
<br>

<% @listing.tag_list.each do |tag|%>

  <a href="/tags/<%= tag %>"> #<%= tag %></a>

<% end %>

<br>

<%= form_for [@listing, @reservation], url: listing_reservations_path(@listing.id) do |form| %>
    <%= render partial: '/reservations/form', locals: {form: form ,listing: @listing }%>





  <% end %>

<div class="btn-group">
  <%= link_to 'Edit', edit_listing_path(@listing.id), class: "btn btn-primary"%>
<!-- < %= link_to 'Delete', user_path(current_user.id), method : :delete %> -->
  <%= link_to "delete", listing_path(@listing.id), method: :delete, data: { confirm: "You sure?" }, class: "btn btn-primary" %>
</div>
<!--
<div class="btn-group">
  < %= link_to edit_listing_path(@listing.id) do %>
    <button type="button" class="btn btn-primary">Edit</button>
  < % end %>
< %= link_to 'Delete', user_path(current_user.id), method : :delete %>
  < %= link_to listing_path(@listing.id), method: :delete, data: { confirm: "You sure?" } do %>
    <button type="button" class="btn btn-primary">Delete</button>
  < % end %>
</div>
 -->