config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  get '/search', to: 'listings#search'

  get 'home/index'

  get 'tags/:tag', to: 'listings#index', as: :tag

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  resources :users, only: [:show, :edit, :update, :destroy]
  resources :listings do
    resources :reservations, only: [:new, :create, :destroy, :show]
  end
  resources :reservations, only: []

  resources :payments

end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User

  has_many :authentications, :dependent => :destroy
  has_many :listings
  has_many :reservations
  mount_uploaders :avatars, AvatarUploader

  def self.create_with_auth_and_hash(authentication,auth_hash)
    create! do |u|
      # u.first_name = auth_hash["info"]["first_name"] This is commented as whatever is here is requested from facebook
      u.email = auth_hash["extra"]["raw_info"]["email"]
      # this following line is a trick to avoid having an empty password field
      u.password = rand(1..9999999999999999)
      u.authentications<<(authentication)
    end
  end

  def fb_token
    x = self.authentications.where(:provider => :facebook).first
    return x.token unless x.nil?
  end

  def password_optional?
    true
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def update
    @user = current_user
    if @user.update(user_params)
      flash[:notice] = "User successfully updated"
      redirect_to user_path(current_user.id)
    else
      flash[:notice] = "Update Failed"
      redirect_to user_path(current_user.id)
    end
  end

  def edit
     @user = current_user
  end

private
  # The following method is called strong params see google
  def user_params
    params.require(:user).permit(:email, :password, {avatars:[]})

  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/edit.html.erb
<%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>
  <%= form.label :upload_picture %>
  <%= form.file_field :avatars, multiple: true %>

    <div class="submit-field">
      <%= form.submit %>
    </div>
<%end%>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class= container>
  <section>
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
        <div class="centerBlock">
          <% if @user.avatars.present? %>
            <%= image_tag (@user.avatars[0].square.url) %>
          <%end%>
        </div>
      </div>
        <br>
      <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 center-elements" style="padding-top:100px; padding-bottom:100px;">
        <div class="text-center">
            <strong><%= @user.email.upcase%></strong>
            <br>
            <br>
          <a class="btn btn-info" href="<%= edit_user_path(current_user.id) %>" role="button">EDIT YOUR PROFILE</a>
        </div>

      </div>
    </div>

    <hr>

    <div class="row">



    </div>

    <div class= "row">


      <% current_user.listings.each do |l|%>
        <% if l.avatars.present? %>
          <a href="/listings/<%=l.id%>"><%=image_tag (l.avatars[0].square.url) %></a> <br>
        <%end%>

        <%= link_to "#{l.title}", listing_path(l.id) %><br>

        <%= l.location %><br>

        <%= l.description %><br>

      <%end%>


    </div>

  </section> <!-- end section 1 -->

  <section>


  </section>





</div> <!-- container div -->