config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  get '/search', to: 'listings#search'

  get 'home/index'

  get 'tags/:tag', to: 'listings#index', as: :tag

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  resources :users, only: [:show, :edit, :update, :destroy]
  resources :listings do
    resources :reservations, only: [:new, :create, :destroy, :show]
  end
  resources :reservations, only: []

  resources :payments

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

    @reservation = Reservation.new
    listings_per_page = 9
    params[:page] = 1 unless params[:page]
    first_listing = (params[:page].to_i - 1 ) * listings_per_page
    listings = Listing.all
    @total_pages = listings.count / listings_per_page
    if listings.count % listings_per_page > 0
      @total_pages += 1
    end
      @listings = listings[first_listing...(first_listing + listings_per_page)]
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class= container-fluid style="padding:0px;">

<%= form_for Listing.new, method: :get, url: search_path, class: "navbar-form navbar-left" do |f| %>
    <%= text_field_tag :term, params[:term], placeholder:"Where do you wanna go?" %>
    <%= f.submit 'search', class: 'btn btn-primary' %>
  <% end %>

<!-- SECTION : Video Module Homepage -->
  <section>
    <div class="video_container">
        <h1><span>Rent unique places to stay from local hosts in 190+ countries.</span><br>Welcome <%=current_user.email if current_user != nil%></h1>
              <video autoplay loop="loop" preload="auto" class="photo">
                 <source src="https://a0.muscache.com/airbnb/static/P1-background-vid-compressed.mp4" type='video/mp4'>
                   <source src="https://a0.muscache.com/airbnb/static/P1-background-vid-compressed.webm" type='video/webm'>
              </video>
    </div>
    <br>
  </section>


<!-- SECTION : Display -->
  <section>
  <br>
    <div class="container">
      <%@listings.each do |l|%>
          <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            <div id= 'listing-location'><h4><%= l.location %></h4></div>
              <%if l.avatars.present? %>
              <div style="width: 100%; height: 270px; background: url(<%= l.avatars[0].square.url %>) no-repeat center; -webkit-background-size: cover; /* pour anciens Chrome et Safari */background-size: cover;;">
              </div>
              <% end %>
            <br>
            <div id= listing-photo-title>
            <%= link_to "#{l.title}", listing_path(l.id) %>
            </div>
            <br>
            <div id= listing-book-button_holder>
              <%= form_for @reservation, url: listing_reservations_path(l) do |form| %>
                <%= render partial: '/reservations/form', locals: {form: form, listing: l }%>
              <% end %>
            </div>
        <!-- < %= link_to 'Delete', user_path(current_user.id), method : :delete %> -->
          </div>
      <%end%>
    </div>
  </section>







        <a href="/listings/new">Create a listing</a>

  <% if current_user %>
  <%=link_to "My Profile", user_path(current_user.id)%>
  <%end%>



  <!-- !!!DAVID THis is a manual way to paginante our listings, but AJAX would make it better. -->

  </div>
  <div id=pagination-block>
    <% (1..@total_pages).each do |page|%>
      <%= link_to page, controller: "home", action: "index", page: page %> &nbsp;
    <% end %>
  </div>

</div>  <!-- End of Container Fluid main page -->