config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  get '/search', to: 'listings#search'

  get 'home/index'

  get 'tags/:tag', to: 'listings#index', as: :tag

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  resources :users, only: [:show, :edit, :update, :destroy]
  resources :listings do
    resources :reservations, only: [:new, :create, :destroy, :show]
  end
  resources :reservations, only: []

  resources :payments

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :user
  belongs_to :listing
  has_many :payments

  mount_uploaders :avatars, AvatarUploader

  #PART OF THE LOGIC OF RESERVATION
  #In your Reservation model, create a method that takes the start date
  # to the end date, and covert it into an array (models/reservation.rb)
def dates
     (start_date..end_date).to_a
end

#Now i would need a method to see which dates are overlapping
# so go to (models/reservation.rb)
    def overlapping_dates(booked_dates)

        dates & booked_dates
    end
#dates refer to the method dates, which is the start and end dates,
#compared it with the existing dates in the array of booked dates,
#if there are any

  def total_calculation

    self.dates.length * self.listing.daily_rate
  end



end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  before_action :set_reservation, only: [ :destroy, :show]


  def new

      @reservation = Reservation.new
      @listing = Listing.find(params[:listing_id])
  end


  # def create
  #
  #   listing = Listing.find(params[:listing_id])
  #   reservation = current_user.reservations.new(reservation_params)

  #   if reservation.save
  #     # I want o go to my listing show page
  #      redirect_to root_path #to change later for a reservation summmary page
  #   else
  #     root_path
  #   end

  # end

  def create
    @listing = Listing.find(params[:listing_id])
    @reservation = current_user.reservations.new(reservation_params)
    booked_dates = @listing.booked_dates
    @host = "david.nextacademy@gmail.com"

      if @reservation.overlapping_dates(booked_dates).empty? && @reservation.save
        #this checks if the booked_dates are empty, if is empty then it will create
        #a new reservation
        #once im able to create a new reservation, i would need to add my listing_id
        #into my reservation as i only have user_id for now (current_user.reservations)
        @reservation.update(listing_id: @listing.id)
        @reservation.update(total: @reservation.total_calculation)
        # ReservationMailer to send a notification email after save
        #
        @host = "david.nextacademy@gmail.com"
            #DAVID !!!!
            #If I want to use mailer then uncomment line below!!!
          # ReservationMailer.notification_email("david.nextacademy@gmail.com", "david.nextacademy@gmail.com", 1, 1).deliver_now
          #ReservationJob.perform_now("david.nextacademy@gmail.com", "david.nextacademy@gmail.com", 1, 1)

          # IF I WANT TO USE REDIS AND SIDEKIQ THEN USE line below
          # ReservationJob.perform_now(current_user.email, @host, @reservation.listing.id, @reservation.id)
           # ReservationMailer.notification_email(current_user.email, @host, @reservation.listing.id, @reservation.id).deliver_later
          # call out reservation job to perform the mail sending task after @reservation is successfully saved
            redirect_to listing_reservation_path(@listing.id, @reservation.id)
        else
          flash[:notice] = "dates are no available on #{@reservation.overlapping_dates(booked_dates).join(", ")}"
          redirect_to root_path
        end
  end

  def show
  end


  def destroy



  end #end of class





private
  # The following method is called strong params see google
  def reservation_params
    params.require(:reservation).permit(:start_date, :end_date, :confirmation_status, :guest_count, :total, :user_id, :listing_id)

  end

  def set_reservation
    @reservation = Reservation.find(params[:id])

  end

end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
  <!-- Trigger the modal with a button -->
  <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#reservation-<%= listing.id %>">Book it now!</button>

  <!-- Modal -->
  <div class="modal fade" id="reservation-<%= listing.id %>" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">Hello <%=current_user.email if current_user%>, what are your dates?</h4>
        </div>
        <div class="modal-body">
          <div class= "parent-box">
            <div class="form-group">
              <%= form.label :When_would_you_arrive? %>
                <script>
                // var disabledates =
                //   function DisableSpecificDates(date) {
                //     var string = jQuery.datepicker.formatDate('dd-mm-yy', date);
                //     return [disableddates.indexOf(string) == -1];
                //   }
                  $(function() {
                    $("#resa_datepicker_start-<%= listing.id %>").datepicker({
                      // beforeShowDay: DisableSpecificDates
                      dateFormat: 'dd-mm-yy',
                      altField: "#resa_datepicker_start_input",
                      altFormat: "dd-mm-yy" }).val();
                  });
                </script>
     <!--  THIS IS THE HTML EQUIVALENT OF THE RAILS BELOW
     <input type="text" id="datepicker" name="reservation[start_date]"> -->
                <div id="resa_datepicker_start-<%= listing.id %>"></div>
                <%= form.hidden_field :start_date, class: "form-control", id: "resa_datepicker_start_input" %>

            </div>

            <div class="form-group">
                <%= form.label :When_would_you_leave? %>
                <script>
                // var disabledates = < %=l.unavdate%>
                  $(function() {
                    $("#resa_datepicker_end-<%= listing.id %>" ).datepicker({
                      dateFormat: 'dd-mm-yy',
                      altField: "#resa_datepicker_end_input",
                      altFormat: "dd-mm-yy" }).val();
                  } );
                </script>
                <div id="resa_datepicker_end-<%= listing.id %>"></div>
                <%= form.hidden_field :end_date, class: "form-control", id: "resa_datepicker_end_input" %>
            </div>
          </div>

          <div class="form-group">
            <%= form.label :How_many_people_are_staying?%>
            <!-- <label for="sel1">Select list:</label> -->
            <%= form.select :guest_count, options_for_select([ 1, 2, 3, 4 ], 1), class: "form-control", id: "guest_count" %>
          </div>


          <p>Some text in the modal.</p>
        </div>
        <div class="modal-footer">
          <div class="submit-field">
            <%= form.submit "Create Now", class: "btn btn-default"%>
          </div>
        </div>
      </div>

    </div>
  </div>











<!-- <div class="form-group">
    <  %= form.label :confirmation_status %>
    <  %= form.check_box :confirmation_status, class: "form-control" %>
</div> -->
<!--


<div class="form-group">
    < %= form.label :guest_count %>
    < %= form.number_field :guest_count, class: "form-control" %>
</div>


< %= @listing.daily_rate %>
<div class="form-group">
    < % = form.label :daily_rate %>
    < %= form.number_field :daily_rate, class: "form-control" %>
</div>

<! <div class="form-group">
    <  %= form.label :total %>
    <  %= form.number_field :total, class: "form-control"%>
</div> -->

app/views/reservations/new.html.erb
This is my New reservation page

<!-- Nested routes implies the pointing to the specific url because it is not the default Url -->
<%= form_for @reservation, url: listing_reservations_path do |form| %>
    <%= render partial: '/reservations/form', object: form %>

    <div class="submit-field">
      <%= form.submit "Create Now", class: "btn btn-default"%>
    </div>

  <% end %>

app/views/reservations/show.html.erb
<h3>Your Reservation</h3>

<ul class="list-group">
  <li class="list-group-item">
    <p>Listing name: <%= link_to @reservation.listing.title, listing_path(@reservation.listing) %></p>
    <p>No. of Guest: <%= @reservation.guest_count%> </p>
    <p>Location: <%= @reservation.listing.location %> </p>
    <p>Check-in Date: <%= @reservation.start_date %></p>

    <p>Checkout Date: <%= @reservation.end_date %></p>

    <p>Total Price: <%= @reservation.total%></p>

    <strong>Payment Status:</strong>
      <% if @reservation.payments.where(status: :authorized).count == 0%>
      <span class="btn btn-danger"> NOT PAID </span>

       <%= link_to 'Pay Now' , new_payment_path + "?id=" + @reservation.id.to_s, class: "btn btn-warning"  %>
      <% else %>
      <span class="btn btn-success">PAID</span>
      <% end %>
  </li>
</ul>